[build]
  publish = "client/dist"
  command = "cd client && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_WHATSAPP_NUMBER = "213698997346"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5000
  publish = "client/dist"